# version: 0.2

# phases: 
#   install:
#     commands:
#       - echo install
#   pre_build:
#     commands:
#       - echo pre build
#   build:
#     commands:
#       - echo build
#   post_build:
#     commands:
#       - echo post build test

# ---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli

  build:
    commands:
      - npm install
      - ng build --prod
      - aws s3 sync dist s3://maximumgrowth

artifacts:
  files:
    - '**/*'

  name: AngularBuild

  discard-paths: yes



  